---
# tasks file for timezone
- name: service_facts
  service_facts:
  tags:
    - timezone
    - facts

- name: /etc/localtime
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
  notify:
    - timedatectl set-timezone
    - cron restart
  tags:
    - timezone
    - localtime

- name: /etc/timezone
  template:
    src: timezone.j2
    dest: /etc/timezone
  notify:
    - timedatectl set-timezone
    - cron restart
  tags:
    - timezone
