---
# tasks file for timezone
- name: /etc/localtime
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
  tags:
    - timezone
    - localtime

- name: /etc/timezone
  template:
    src: timezone.j2
    dest: /etc/timezone
  tags:
    - timezone
...
