---
# tasks file for timezone
- name: Service facts
  ansible.builtin.service_facts:
  tags:
    - timezone
    - facts

- name: /etc/localtime
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
  notify:
    - Set timezone
    - Cron restart
  tags:
    - timezone
    - localtime

- name: /etc/timezone
  ansible.builtin.template:
    src: timezone.j2
    dest: /etc/timezone
    mode: 0644
  notify:
    - Set timezone
    - Cron restart
  tags:
    - timezone
