---
# handlers file for timezone
- name: Set-timezone
  command: 'timedatectl set-timezone {{ timezone }}'
  when:
    - ansible_virtualization_type != 'lxc'

- name: Cron restart
  service:
    name: cron
    state: restarted
  when:
    - "'cron' in services"
    - ansible_facts.services['cron']['state'] == 'running'
