---
# handlers file for timezone
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when:
    - ansible_virtualization_type != 'lxc'

- name: Cron restart
  ansible.builtin.service:
    name: cron
    state: restarted
  when:
    - "'cron' in services"
    - ansible_facts.services['cron']['state'] == 'running'
